#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('LZXPRESS',
        deps='replace',
	source='lzxpress.c'
	)

bld.SAMBA_SUBSYSTEM('LZHUFFXPRESS',
        deps='talloc replace',
	source='lzhuff_xpress.c xpress_huff_compress.c'
	)
